name: Tests with Allure Report per PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Setup Node.js for Allure 3
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 24

      - name: Install Allure 3 CLI
        run: npm install -g allure

      - name: Generate Allure 3 Report with history
        run: npx allure run --config=./allurerc.js -- "uv run pytest"

      - name: Deploy Allure report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: ''
          keep_files: true
          exclude_assets: ""

      - name: Comment PR with Allure Report link
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ Allure report for this PR is available [here](https://nottezz.github.io/API-e2e-tests-examples/)